"""Export the derived knowledge graph as an offline, self-contained HTML bundle.

Run from any directory: python /path/to/repo/viewer/export.py [--allow-stale].
The bundle opens from the local filesystem (file://) with no server or network:
the graph is embedded as a script, and Cytoscape.js is vendored.

The viewer reads graph/generated/knowledge.json; it never regenerates or edits it.
It lives outside graph/ because graph/build.py hashes every file under graph/ into
the snapshot revision, and a presentation layer must not move that revision.
"""

import argparse
import hashlib
import importlib.util
import json
import shutil
import subprocess
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VIEWER = Path(__file__).resolve().parent
EXPORTER_VERSION = "1.0"
# Fixed member timestamp keeps the zip byte-identical for an identical bundle.
ZIP_DATE = (1980, 1, 1, 0, 0, 0)


class ViewerError(ValueError):
    """The graph cannot be exported as requested."""


def load_build(root):
    spec = importlib.util.spec_from_file_location(
        "knowledge_build", root / "graph/build.py"
    )
    build = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(build)
    return build


def git_state(root):
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=root, text=True, stderr=subprocess.DEVNULL
        ).strip()
        status = subprocess.check_output(
            ["git", "status", "--porcelain"], cwd=root, text=True
        )
    except (OSError, subprocess.CalledProcessError):
        return None, None
    return commit, bool(status.strip())


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def script_json(value):
    # "</" would let embedded text close the <script> element early.
    return json.dumps(value, indent=1, sort_keys=True, ensure_ascii=False).replace(
        "</", "<\\/"
    )


def export(graph_path=None, out_dir=None, allow_stale=False, make_zip=True, root=ROOT):
    root = Path(root)
    graph_path = Path(graph_path or root / "graph/generated/knowledge.json")
    out_dir = Path(out_dir or root / "outputs")
    if not graph_path.exists():
        raise ViewerError(f"{graph_path} not found; run graph/build.py")
    graph_bytes = graph_path.read_bytes()
    graph = json.loads(graph_bytes)

    build = load_build(root)
    fresh = graph_bytes == build.canonical_bytes(build.generate(root))
    if not fresh and not allow_stale:
        raise ViewerError(
            f"{graph_path} is stale against the corpus; run graph/build.py "
            "(or pass --allow-stale to export it with a stale banner)"
        )

    commit, dirty = git_state(root)
    meta = {
        "candidate_relationship_count": len(graph["candidate_relationships"]),
        "exporter_version": EXPORTER_VERSION,
        "forest_cover_lab_dirty": dirty,
        "forest_cover_lab_revision": commit,
        "fresh": fresh,
        "graph_revision": graph["revision"],
        "graph_sha256": hashlib.sha256(graph_bytes).hexdigest(),
        "node_count": len(graph["nodes"]),
        "relationship_count": len(graph["relationships"]),
        "schema_version": graph["schema_version"],
    }

    name = f"kg-viewer-{graph['revision'][:12]}"
    bundle = out_dir / name
    if bundle.exists():
        shutil.rmtree(bundle)
    shutil.copytree(VIEWER / "templates", bundle)
    shutil.copytree(VIEWER / "vendor", bundle / "vendor")
    (bundle / "data.js").write_text(
        "// Generated by viewer/export.py from graph/generated/knowledge.json.\n"
        "// Derived index for browsing; not an independent scientific record.\n"
        f"window.KG_BUNDLE = {script_json({'graph': graph, 'meta': meta})};\n",
        encoding="utf-8",
    )
    (bundle / "README.txt").write_text(
        f"Forest Cover Lab knowledge graph viewer ({name})\n\n"
        "Open index.html (graph) or catalogue.html (tables) in a web browser.\n"
        "Everything is local: no server, network or installation is needed.\n\n"
        f"Graph revision: {graph['revision']}\n"
        f"Forest Cover Lab commit: {commit or 'unknown'}"
        f"{' (dirty working tree)' if dirty else ''}\n"
        f"Fresh against corpus at export: {'yes' if fresh else 'NO (stale)'}\n\n"
        "The graph is a deterministic index derived from the knowledge/ corpus.\n"
        "Its SHA-256 identifies a snapshot; it is not evidence of scientific\n"
        "validation. Candidate relationships are shown dashed and are not\n"
        "validated knowledge. Cytoscape.js is MIT licensed (vendor/).\n",
        encoding="utf-8",
    )
    files = sorted(
        p for p in bundle.rglob("*") if p.is_file() and p.name != "manifest.json"
    )
    manifest = {
        "files": {p.relative_to(bundle).as_posix(): sha256(p) for p in files},
        "meta": meta,
    }
    (bundle / "manifest.json").write_bytes(build.canonical_bytes(manifest))

    if make_zip:
        archive = out_dir / f"{name}.zip"
        with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
            for path in sorted(p for p in bundle.rglob("*") if p.is_file()):
                info = zipfile.ZipInfo(
                    f"{name}/{path.relative_to(bundle).as_posix()}", ZIP_DATE
                )
                info.compress_type = zipfile.ZIP_DEFLATED
                info.external_attr = 0o644 << 16
                zf.writestr(info, path.read_bytes())
    return bundle


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--graph", type=Path, help="Graph JSON (default: generated)")
    parser.add_argument("--out-dir", type=Path, help="Output root (default: outputs/)")
    parser.add_argument(
        "--allow-stale", action="store_true", help="Export a stale graph with a banner"
    )
    parser.add_argument("--no-zip", action="store_true", help="Skip the zip archive")
    args = parser.parse_args()
    try:
        bundle = export(args.graph, args.out_dir, args.allow_stale, not args.no_zip)
    except (ViewerError, OSError, ValueError) as exc:
        parser.exit(1, f"{exc}\n")
    print(f"Viewer bundle: {bundle}")
    if not args.no_zip:
        print(f"Archive: {bundle.with_suffix('.zip')}")
    print(f"Open: {bundle / 'index.html'}")


if __name__ == "__main__":
    main()
